apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: back-hpa
  namespace: deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-deploy-mounted2
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50