apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy-mounted2
  namespace: deploy
spec:
  selector:
    matchLabels:
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: back-app
        image: 891377163278.dkr.ecr.ap-northeast-2.amazonaws.com/mydata-was:nothing-log-tomcat
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: my-pv
          mountPath: /usr/local/tomcat/webapps/ROOT/data/
        - name: tomcat-logs
          mountPath: /usr/local/tomcat/logs
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
      - name: sidecar-access
        image: docker.elastic.co/beats/filebeat:7.16.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: tomcat-logs
          mountPath: /usr/local/tomcat/logs
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
      volumes:
      - name: my-pv
        persistentVolumeClaim:
          claimName: efs-pvc
      - name: tomcat-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"
