apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy-mounted2
  namespace: deploy
spec:
  selector:
    matchLabels:
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: back-app
        image: 891377163278.dkr.ecr.ap-northeast-2.amazonaws.com/develop-was:view-tomcat
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts: # 생성한 볼륨 마운트
        - name: my-pv
          mountPath: /usr/local/tomcat/webapps/ROOT/data/
          #mountPath: /usr/share
        resources:
          requests:
            cpu: 200m
            memory: 200M
      volumes: # 위에서 생성한 PVC를 이용하여 볼륨 생성
      - name: my-pv
        persistentVolumeClaim:
          claimName: efs-pvc
    #   affinity:
    #     podAntiAffinity:
    #       requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchExpressions:
    #           - key: tier
    #             operator: In
    #             values:
    #             - backend
    #         topologyKey: "kubernetes.io/hostname"
