apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: deploy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc # 위에서 생성한 스토리지 클래스 
  resources:
    requests:
      storage: 1Gi